version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  api:
    image: fizzbuzz-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${API_PORT}:3001"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=debug'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.listen-address=0.0.0.0:${PROMETHEUS_PORT}'
    ports:
      - "${PROMETHEUS_PORT}:9091"
    depends_on:
      - api

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  grafana:
    image: grafana/grafana
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
      GF_SECURITY_ADMIN_USER: 'admin'
      GF_SECURITY_ADMIN_PASSWORD: 'passwd'
      GF_USERS_ALLOW_SIGN_UP: 'false'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "${GRAFANA_PORT}:3000"
    depends_on:
      - prometheus