version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  http:
    driver: bridge
  monitoring-back:
    driver: bridge
  data:
    driver: bridge

services:
  api:
    image: fizzbuzz-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    expose:
      - 3001
    depends_on:
      - redis
    networks:
      - monitoring-back
      - http
      - data

  redis:
    image: redis:7.2.1-alpine
    ports:
      - "6379:6379"
    networks:
      - data

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=debug'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9091:9091"
    expose:
      - 9091
    networks:
      - monitoring-back

  grafana:
    image: grafana/grafana
    user: '472'
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      - prometheus
    networks:
      - monitoring-back