version: '3'
services:
  api:
    image: fizzbuzz-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      - redis

  redis:
    image: redis:7.2.1-alpine
    ports:
      - "6379:6379"
    expose:
      - 6379