swagger: '2.0'
info:
  description: fizz-buzz api
  version: 1.0.0
  title: fizz-buzz api

schemes: [http]
host: localhost
basePath: /
consumes: [application/json]
produces: [application/json]

tags:
  - name: fizzbuzz
    description: fizzbuzz
  - name: monitoring
    description: monitoring
  - name: stats
    description: stats
  - name: metrics
    description: metrics
paths:
  /metrics:
    get:
      tags: [metrics]
      summary: prometheus metrics
      produces:
        - text/plain; charset=utf-8
      responses:
        200:
          description: OK
  /mon/ping:
    get:
      tags: [monitoring]
      summary: Health check
      responses:
        200:
          description: Health OK
          schema:
            properties:
              status:
                default: OK
                type: string
            type: object
        default:
          description: Error handling the request
          schema:
            $ref: '#/definitions/Error'
  /v1/stats:
    get:
      tags: [stats]
      summary: Retrieves the most frequent used request, as well as the number of hits for this request
      responses:
        200:
          description: Retrieves the most frequent used request, as well as the number of hits for this request
          schema:
            $ref: '#/definitions/MostUsedRequest'
        default:
          description: Error handling the request
          schema:
            $ref: '#/definitions/Error'
  /v1/fizzbuzz:
    get:
      tags: [fizzbuzz]
      summary: Performs a fizz-buzz
      operationId: fizzbuzz
      parameters:
        - name: int1
          required: true
          in: query
          type: integer
          format: int
          minimum: 1
          description: number where all of its multiples will be replaced by str1
        - name: int2
          required: true
          in: query
          type: integer
          format: int
          minimum: 1
          description: number where all of its multiples will be replaced by str2
        - name: limit
          required: true
          in: query
          type: integer
          format: int
          description: maximum number until the fizz-buzz will be performed
        - name: str1
          required: true
          in: query
          type: string
          x-nullable: false
          description: string that will replace all multiples of int1
        - name: str2
          required: true
          in: query
          type: string
          description: string that will replace all multiples of int2
          x-nullable: false
      responses:
        200:
          description: fizz buzz string
          schema:
            $ref: '#/definitions/FizzBuzzResponse'
        default:
          description: Error handling the request
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    properties:
      code:
        format: int64
        type: integer
      message:
        type: string
    type: object
  FizzBuzzResponse:
    properties:
      output:
        type: string
  MostUsedRequest:
    properties:
      int1:
        type: integer
        format: int
      int2:
        type: integer
        format: int
      limit:
        type: integer
        format: int
      str1:
        type: string
      str2:
        type: string
      hits:
        type: integer
        format: int
    required:
      - int1
      - int2
      - limit
      - str1
      - str2
      - hits
