global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['127.0.0.1:9091']
  - job_name: app
    scrape_interval: 15s
    static_configs:
      - targets:
        - host.docker.internal:3001
        - localhost:3001
        - api:3001